const data = [
  {
    id: 1,
    name: "Introduction to Computer Science",
    instructor: "John Smith",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/117x100.png/ff4444/ffffff",
    duration: "8 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Columbia University",
    prerequisites: ["PHP", "Rust", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "nisl turpis commodo neque",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content: "nisl turpis commodo neque",
      },
      {
        week: 3,
        topic: "Artificial Intelligence",
        content: "Lorem ipsum dolor sit amet",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "rkearney0@va.gov" },
      { id: 2, name: "Emma Wilson", email: "sdeye1@godaddy.com" },
      { id: 3, name: "John Smith", email: "idealey2@blogspot.com" },
    ],
  },
  {
    id: 2,
    name: "Data Structures and Algorithms",
    instructor: "Emily Johnson",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/129x100.png/dddddd/000000",
    duration: "4 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Yale University",
    prerequisites: ["Go", "Rust"],
    syllabus: [
      {
        week: 1,
        topic: "Software Engineering",
        content: "nisl turpis commodo neque",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content: "nunc id aliquam fermentum",
      },
    ],
    students: [{ id: 1, name: "Emma Wilson", email: "amaundrell0@usgs.gov" }],
  },
  {
    id: 3,
    name: "Operating Systems",
    instructor: "Michael Davis",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/128x100.png/cc0000/ffffff",
    duration: "4 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of Oxford",
    prerequisites: ["Go", "Swift"],
    syllabus: [
      { week: 1, topic: "Cybersecurity", content: "est urna feugiat justo" },
      {
        week: 2,
        topic: "Introduction to Computer Science",
        content: "mi nec ultrices tristique",
      },
      {
        week: 3,
        topic: "Data Structures and Algorithms",
        content: "nisl turpis commodo neque",
      },
      {
        week: 4,
        topic: "Artificial Intelligence",
        content: "mi nec ultrices tristique",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "imicheli0@shareasale.com" },
      { id: 2, name: "Michael Davis", email: "ddoget1@google.com.hk" },
    ],
  },
  {
    id: 4,
    name: "Database Management Systems",
    instructor: "Jessica Wilson",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/109x100.png/cc0000/ffffff",
    duration: "12 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Stanford University",
    prerequisites: ["Go", "Rust"],
    syllabus: [
      {
        week: 1,
        topic: "Computer Networks",
        content: "nisl turpis commodo neque",
      },
      {
        week: 2,
        topic: "Software Engineering",
        content: "mi nec ultrices tristique",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "kdawtre0@chicagotribune.com" },
      { id: 2, name: "Daniel Thompson", email: "ogoodman1@wordpress.org" },
      { id: 3, name: "Emily Johnson", email: "mscimone2@google.pl" },
      { id: 4, name: "Emily Johnson", email: "dboller3@wsj.com" },
      { id: 5, name: "Daniel Thompson", email: "rbuey4@noaa.gov" },
    ],
  },
  {
    id: 5,
    name: "Artificial Intelligence",
    instructor: "David Thompson",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/238x100.png/5fa2dd/ffffff",
    duration: "8 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of Toronto",
    prerequisites: ["JavaScript", "Swift", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "est urna feugiat justo",
      },
      {
        week: 2,
        topic: "Introduction to Computer Science",
        content: "lobortis nunc sed",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "aastley0@dropbox.com" },
      { id: 2, name: "Daniel Thompson", email: "kfrediani1@ibm.com" },
      { id: 3, name: "Emily Johnson", email: "ofeldmann2@sogou.com" },
      { id: 4, name: "Emily Johnson", email: "jclogg3@rediff.com" },
      { id: 5, name: "Emma Wilson", email: "ksikorski4@rambler.ru" },
      { id: 6, name: "John Smith", email: "wduthy5@apache.org" },
    ],
  },
  {
    id: 6,
    name: "Computer Networks",
    instructor: "Sarah Anderson",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/121x100.png/cc0000/ffffff",
    duration: "8 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of Toronto",
    prerequisites: ["Ruby", "Go", "C++"],
    syllabus: [
      { week: 1, topic: "Cybersecurity", content: "nunc id aliquam fermentum" },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content: "nisl turpis commodo neque",
      },
      {
        week: 3,
        topic: "Introduction to Computer Science",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "afinci0@icq.com" },
      { id: 2, name: "Daniel Thompson", email: "mdayment1@chicagotribune.com" },
      { id: 3, name: "Michael Davis", email: "fmepsted2@wix.com" },
      { id: 4, name: "Daniel Thompson", email: "mderbyshire3@umich.edu" },
      { id: 5, name: "Daniel Thompson", email: "jfellenor4@lulu.com" },
    ],
  },
  {
    id: 7,
    name: "Software Engineering",
    instructor: "Daniel Martinez",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/212x100.png/cc0000/ffffff",
    duration: "10 weeks",
    Schedule: "Tuesday-Saturday",
    location: "University of Oxford",
    prerequisites: ["Swift", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Database Management Systems",
        content: "nunc id aliquam fermentum",
      },
      {
        week: 2,
        topic: "Software Engineering",
        content:
          "consectetur adipiscing elit. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "lolivello0@aol.com" },
      { id: 2, name: "Emily Johnson", email: "aknill1@wp.com" },
      { id: 3, name: "Daniel Thompson", email: "fgibbeson2@myspace.com" },
      { id: 4, name: "John Smith", email: "bboame3@imgur.com" },
      { id: 5, name: "Daniel Thompson", email: "hcanlin4@webs.com" },
    ],
  },
  {
    id: 8,
    name: "Web Development",
    instructor: "Olivia Taylor",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/191x100.png/5fa2dd/ffffff",
    duration: "8 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of Oxford",
    prerequisites: ["Rust", "Python", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Computer Networks",
        content: "nunc id aliquam fermentum",
      },
      {
        week: 2,
        topic: "Web Development",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "htorra0@cornell.edu" },
      { id: 2, name: "Michael Davis", email: "mfaux1@fda.gov" },
      { id: 3, name: "Daniel Thompson", email: "kpeare2@google.co.uk" },
    ],
  },
  {
    id: 9,
    name: "Machine Learning",
    instructor: "Matthew Hernandez",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/111x100.png/5fa2dd/ffffff",
    duration: "8 weeks",
    Schedule: "Monday-Friday",
    location: "Princeton University",
    prerequisites: ["PHP", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Data Structures and Algorithms",
        content: "est urna feugiat justo",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "epethick0@mac.com" },
      { id: 2, name: "John Smith", email: "cbygrove1@ftc.gov" },
      { id: 3, name: "John Smith", email: "laliman2@oakley.com" },
      { id: 4, name: "Emily Johnson", email: "nfaustian3@example.com" },
    ],
  },
  {
    id: 10,
    name: "Cybersecurity",
    instructor: "Sophia Moore",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/177x100.png/cc0000/ffffff",
    duration: "12 weeks",
    Schedule: "Tuesday-Saturday",
    location: "University of Oxford",
    prerequisites: ["Java", "PHP"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "mi nec ultrices tristique",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "lvalenta0@scribd.com" },
      { id: 2, name: "Emily Johnson", email: "ktamburi1@mashable.com" },
      { id: 3, name: "Daniel Thompson", email: "pmcmeekin2@ft.com" },
      { id: 4, name: "Daniel Thompson", email: "gspata3@123-reg.co.uk" },
      { id: 5, name: "Daniel Thompson", email: "amcallaster4@loc.gov" },
    ],
  },
  {
    id: 11,
    name: "Introduction to Computer Science",
    instructor: "Andrew Clark",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/103x100.png/dddddd/000000",
    duration: "10 weeks",
    Schedule: "Monday-Friday",
    location: "Stanford University",
    prerequisites: ["JavaScript", "Ruby", "Rust"],
    syllabus: [
      {
        week: 1,
        topic: "Machine Learning",
        content: "Lorem ipsum dolor sit amet",
      },
      {
        week: 2,
        topic: "Artificial Intelligence",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      { week: 3, topic: "Computer Networks", content: "lobortis nunc sed" },
      {
        week: 4,
        topic: "Operating Systems",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "ebruin0@xrea.com" },
      { id: 2, name: "John Smith", email: "slain1@discuz.net" },
      { id: 3, name: "Emma Wilson", email: "cohanlon2@nih.gov" },
      { id: 4, name: "Emma Wilson", email: "mspacy3@gnu.org" },
      { id: 5, name: "John Smith", email: "ebispham4@dailymail.co.uk" },
      { id: 6, name: "John Smith", email: "hleslie5@google.it" },
    ],
  },
  {
    id: 12,
    name: "Data Structures and Algorithms",
    instructor: "Emma Lewis",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/104x100.png/dddddd/000000",
    duration: "8 weeks",
    Schedule: "Monday-Friday",
    location: "Columbia University",
    prerequisites: ["Rust", "Go", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Web Development",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      { week: 2, topic: "Web Development", content: "lobortis nunc sed" },
    ],
    students: [
      { id: 1, name: "John Smith", email: "vandrock0@amazon.com" },
      { id: 2, name: "Emma Wilson", email: "labbets1@youku.com" },
      { id: 3, name: "Emma Wilson", email: "jdampier2@opensource.org" },
      { id: 4, name: "Emily Johnson", email: "amowat3@constantcontact.com" },
      { id: 5, name: "Emma Wilson", email: "bquidenham4@engadget.com" },
      { id: 6, name: "Michael Davis", email: "mpetrus5@nifty.com" },
    ],
  },
  {
    id: 13,
    name: "Operating Systems",
    instructor: "Christopher Walker",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/103x100.png/cc0000/ffffff",
    duration: "6 weeks",
    Schedule: "Monday-Friday",
    location: "Columbia University",
    prerequisites: ["PHP", "Java"],
    syllabus: [
      {
        week: 1,
        topic: "Software Engineering",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "rhannum0@reverbnation.com" },
      { id: 2, name: "Emily Johnson", email: "bsherrett1@sourceforge.net" },
      { id: 3, name: "Michael Davis", email: "bgilliver2@ovh.net" },
      { id: 4, name: "Daniel Thompson", email: "eminocchi3@theguardian.com" },
      { id: 5, name: "John Smith", email: "kpeterffy4@tuttocitta.it" },
      { id: 6, name: "Michael Davis", email: "mgieves5@google.ca" },
    ],
  },
  {
    id: 14,
    name: "Database Management Systems",
    instructor: "Ava Hall",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/145x100.png/cc0000/ffffff",
    duration: "10 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Stanford University",
    prerequisites: ["Go", "Java", "Swift"],
    syllabus: [
      { week: 1, topic: "Cybersecurity", content: "nisl turpis commodo neque" },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "amaystone0@abc.net.au" },
      { id: 2, name: "Emma Wilson", email: "mspread1@blog.com" },
      { id: 3, name: "Daniel Thompson", email: "bnaismith2@deviantart.com" },
      { id: 4, name: "Michael Davis", email: "ehischke3@pagesperso-orange.fr" },
      { id: 5, name: "Daniel Thompson", email: "agallier4@ycombinator.com" },
    ],
  },
  {
    id: 15,
    name: "Artificial Intelligence",
    instructor: "Joshua Young",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/114x100.png/5fa2dd/ffffff",
    duration: "8 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Columbia University",
    prerequisites: ["C++", "JavaScript"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content: "nunc id aliquam fermentum",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 3,
        topic: "Artificial Intelligence",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 4,
        topic: "Web Development",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "epitkaithly0@oaic.gov.au" },
      { id: 2, name: "Emma Wilson", email: "ykilgrove1@delicious.com" },
      { id: 3, name: "Emily Johnson", email: "wend2@discovery.com" },
      { id: 4, name: "Emily Johnson", email: "ylintill3@people.com.cn" },
    ],
  },
  {
    id: 16,
    name: "Computer Networks",
    instructor: "Isabella Allen",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/135x100.png/cc0000/ffffff",
    duration: "4 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Stanford University",
    prerequisites: ["JavaScript", "Swift", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Web Development",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 2,
        topic: "Computer Networks",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "ntramel0@un.org" },
      { id: 2, name: "Michael Davis", email: "fvuittet1@trellian.com" },
      { id: 3, name: "Emily Johnson", email: "kcordaroy2@springer.com" },
      { id: 4, name: "Emma Wilson", email: "aroddick3@lulu.com" },
      { id: 5, name: "Daniel Thompson", email: "vstocker4@tinyurl.com" },
      {
        id: 6,
        name: "Michael Davis",
        email: "kphilipart5@networkadvertising.org",
      },
    ],
  },
  {
    id: 17,
    name: "Software Engineering",
    instructor: "Joseph Rodriguez",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/181x100.png/dddddd/000000",
    duration: "12 weeks",
    Schedule: "Monday-Friday",
    location: "Columbia University",
    prerequisites: ["Python", "Swift"],
    syllabus: [
      {
        week: 1,
        topic: "Web Development",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
      {
        week: 2,
        topic: "Introduction to Computer Science",
        content: "lobortis nunc sed",
      },
      {
        week: 3,
        topic: "Web Development",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus.",
      },
      { week: 4, topic: "Cybersecurity", content: "nunc id aliquam fermentum" },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "lleppard0@amazon.co.jp" },
      { id: 2, name: "Daniel Thompson", email: "lmoehle1@paypal.com" },
      { id: 3, name: "Emma Wilson", email: "nneissen2@tripod.com" },
      { id: 4, name: "Emily Johnson", email: "gpuddin3@nasa.gov" },
    ],
  },
  {
    id: 18,
    name: "Web Development",
    instructor: "Mia King",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/148x100.png/dddddd/000000",
    duration: "6 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Princeton University",
    prerequisites: ["JavaScript", "Go", "Swift"],
    syllabus: [
      {
        week: 1,
        topic: "Database Management Systems",
        content: "mi nec ultrices tristique",
      },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content: "lobortis nunc sed",
      },
    ],
    students: [
      { id: 1, name: "Daniel Thompson", email: "scory0@phpbb.com" },
      { id: 2, name: "Daniel Thompson", email: "kmoakson1@examiner.com" },
      { id: 3, name: "John Smith", email: "bnote2@gravatar.com" },
      { id: 4, name: "Emily Johnson", email: "cboots3@hud.gov" },
    ],
  },
  {
    id: 19,
    name: "Machine Learning",
    instructor: "William Wright",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/173x100.png/ff4444/ffffff",
    duration: "6 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Columbia University",
    prerequisites: ["Go", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Data Structures and Algorithms",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "wocurrigan0@163.com" },
      { id: 2, name: "Emma Wilson", email: "lzanelli1@lycos.com" },
    ],
  },
  {
    id: 20,
    name: "Cybersecurity",
    instructor: "Abigail Hill",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/195x100.png/ff4444/ffffff",
    duration: "6 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Yale University",
    prerequisites: ["C++", "Go", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Artificial Intelligence",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
    ],
    students: [{ id: 1, name: "John Smith", email: "edohr0@paginegialle.it" }],
  },
  {
    id: 21,
    name: "Introduction to Computer Science",
    instructor: "James Scott",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/237x100.png/cc0000/ffffff",
    duration: "12 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Columbia University",
    prerequisites: ["PHP", "C++", "Java"],
    syllabus: [
      {
        week: 1,
        topic: "Artificial Intelligence",
        content: "est urna feugiat justo",
      },
      {
        week: 2,
        topic: "Machine Learning",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "estobo0@army.mil" },
      { id: 2, name: "Emma Wilson", email: "troberts1@soundcloud.com" },
    ],
  },
  {
    id: 22,
    name: "Data Structures and Algorithms",
    instructor: "Emily Green",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/137x100.png/5fa2dd/ffffff",
    duration: "4 weeks",
    Schedule: "Monday-Friday",
    location: "Harvard University",
    prerequisites: ["Java", "Swift"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "est urna feugiat justo",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content: "nunc id aliquam fermentum",
      },
      {
        week: 3,
        topic: "Introduction to Computer Science",
        content: "est urna feugiat justo",
      },
      {
        week: 4,
        topic: "Computer Networks",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "nseathwright0@timesonline.co.uk" },
      { id: 2, name: "Daniel Thompson", email: "hhallatt1@berkeley.edu" },
      { id: 3, name: "Daniel Thompson", email: "ocribbins2@feedburner.com" },
    ],
  },
  {
    id: 23,
    name: "Operating Systems",
    instructor: "David Adams",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/243x100.png/5fa2dd/ffffff",
    duration: "4 weeks",
    Schedule: "Monday-Friday",
    location: "Yale University",
    prerequisites: ["Go", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Web Development",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "kolongain0@upenn.edu" },
      { id: 2, name: "Emma Wilson", email: "sforson1@un.org" },
    ],
  },
  {
    id: 24,
    name: "Database Management Systems",
    instructor: "Charlotte Baker",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/250x100.png/dddddd/000000",
    duration: "12 weeks",
    Schedule: "Tuesday-Saturday",
    location: "University of Oxford",
    prerequisites: ["Go", "Python"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content: "est urna feugiat justo",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "ahuddleston0@cdc.gov" },
      { id: 2, name: "Emily Johnson", email: "jdurrance1@google.nl" },
      {
        id: 3,
        name: "Emily Johnson",
        email: "jbillsberry2@huffingtonpost.com",
      },
    ],
  },
  {
    id: 25,
    name: "Artificial Intelligence",
    instructor: "Daniel Turner",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/200x100.png/dddddd/000000",
    duration: "10 weeks",
    Schedule: "Monday-Friday",
    location: "University of Cambridge",
    prerequisites: ["Java", "Python", "JavaScript"],
    syllabus: [
      { week: 1, topic: "Cybersecurity", content: "nisl turpis commodo neque" },
      {
        week: 2,
        topic: "Software Engineering",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 3,
        topic: "Introduction to Computer Science",
        content: "lobortis nunc sed",
      },
      { week: 4, topic: "Machine Learning", content: "est urna feugiat justo" },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "rbeenham0@fastcompany.com" },
    ],
  },
  {
    id: 26,
    name: "Computer Networks",
    instructor: "Grace Carter",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/162x100.png/ff4444/ffffff",
    duration: "4 weeks",
    Schedule: "Monday-Friday",
    location: "University of Toronto",
    prerequisites: ["Python", "Swift", "JavaScript"],
    syllabus: [
      {
        week: 1,
        topic: "Data Structures and Algorithms",
        content: "nunc id aliquam fermentum",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "mhaddington0@wisc.edu" },
      { id: 2, name: "Emily Johnson", email: "mkenealy1@twitpic.com" },
      { id: 3, name: "Daniel Thompson", email: "vcrosoer2@dagondesign.com" },
      { id: 4, name: "Emma Wilson", email: "dcescot3@stumbleupon.com" },
    ],
  },
  {
    id: 27,
    name: "Software Engineering",
    instructor: "Michael White",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/118x100.png/cc0000/ffffff",
    duration: "12 weeks",
    Schedule: "Monday-Friday",
    location: "University of Toronto",
    prerequisites: ["Python", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Artificial Intelligence",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 2,
        topic: "Artificial Intelligence",
        content: "nunc id aliquam fermentum",
      },
      {
        week: 3,
        topic: "Web Development",
        content: "nisl turpis commodo neque",
      },
      {
        week: 4,
        topic: "Data Structures and Algorithms",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus.",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "dlinzee0@netlog.com" },
      { id: 2, name: "Emily Johnson", email: "fbartolomeazzi1@linkedin.com" },
    ],
  },
  {
    id: 28,
    name: "Web Development",
    instructor: "Samantha Mitchell",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/109x100.png/ff4444/ffffff",
    duration: "12 weeks",
    Schedule: "Monday-Friday",
    location: "Yale University",
    prerequisites: ["Go", "Swift", "PHP"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus.",
      },
      {
        week: 2,
        topic: "Software Engineering",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "ewalrond0@theatlantic.com" },
      { id: 2, name: "Michael Davis", email: "jairth1@exblog.jp" },
      { id: 3, name: "John Smith", email: "bsauvan2@google.de" },
    ],
  },
  {
    id: 29,
    name: "Machine Learning",
    instructor: "Alexander Nelson",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/153x100.png/5fa2dd/ffffff",
    duration: "4 weeks",
    Schedule: "Monday-Friday",
    location: "Yale University",
    prerequisites: ["PHP", "Python", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Software Engineering",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 2,
        topic: "Machine Learning",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 3,
        topic: "Artificial Intelligence",
        content:
          "consectetur adipiscing elit. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "mkempshall0@dedecms.com" },
    ],
  },
  {
    id: 30,
    name: "Cybersecurity",
    instructor: "Madison Cooper",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/107x100.png/5fa2dd/ffffff",
    duration: "8 weeks",
    Schedule: "Monday-Friday",
    location: "Harvard University",
    prerequisites: ["Rust", "C++"],
    syllabus: [
      { week: 1, topic: "Computer Networks", content: "lobortis nunc sed" },
      {
        week: 2,
        topic: "Operating Systems",
        content: "nisl turpis commodo neque",
      },
      {
        week: 3,
        topic: "Data Structures and Algorithms",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 4,
        topic: "Software Engineering",
        content: "est urna feugiat justo",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "llowes0@t.co" },
      { id: 2, name: "John Smith", email: "tgooddie1@linkedin.com" },
    ],
  },
  {
    id: 31,
    name: "Introduction to Computer Science",
    instructor: "Ethan Roberts",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/205x100.png/5fa2dd/ffffff",
    duration: "12 weeks",
    Schedule: "Monday-Friday",
    location: "University of Oxford",
    prerequisites: ["Python", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Artificial Intelligence",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 3,
        topic: "Introduction to Computer Science",
        content: "lobortis nunc sed",
      },
      {
        week: 4,
        topic: "Web Development",
        content: "Lorem ipsum dolor sit amet",
      },
    ],
    students: [
      { id: 1, name: "Daniel Thompson", email: "jdarby0@deviantart.com" },
      { id: 2, name: "Emily Johnson", email: "brummins1@ucoz.com" },
    ],
  },
  {
    id: 32,
    name: "Data Structures and Algorithms",
    instructor: "Olivia Cook",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/129x100.png/dddddd/000000",
    duration: "8 weeks",
    Schedule: "Monday-Friday",
    location: "Yale University",
    prerequisites: ["Rust", "JavaScript"],
    syllabus: [
      {
        week: 1,
        topic: "Data Structures and Algorithms",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus.",
      },
      {
        week: 3,
        topic: "Operating Systems",
        content: "Lorem ipsum dolor sit amet",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "lknight0@dailymotion.com" },
      { id: 2, name: "Michael Davis", email: "ekeme1@dmoz.org" },
    ],
  },
  {
    id: 33,
    name: "Operating Systems",
    instructor: "Benjamin Morris",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/123x100.png/ff4444/ffffff",
    duration: "8 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Columbia University",
    prerequisites: ["Swift", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content: "lobortis nunc sed",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content: "nunc id aliquam fermentum",
      },
    ],
    students: [{ id: 1, name: "Emily Johnson", email: "mlyburn0@taobao.com" }],
  },
  {
    id: 34,
    name: "Database Management Systems",
    instructor: "Elizabeth Rivera",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/159x100.png/cc0000/ffffff",
    duration: "8 weeks",
    Schedule: "Monday-Friday",
    location: "University of California",
    prerequisites: ["Python", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "Lorem ipsum dolor sit amet",
      },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
      {
        week: 3,
        topic: "Introduction to Computer Science",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "adenyukin0@dot.gov" },
      { id: 2, name: "John Smith", email: "fgladwish1@webeden.co.uk" },
      { id: 3, name: "Emily Johnson", email: "rcarass2@arstechnica.com" },
      { id: 4, name: "John Smith", email: "mheaker3@networksolutions.com" },
    ],
  },
  {
    id: 35,
    name: "Artificial Intelligence",
    instructor: "Jacob Reed",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/133x100.png/ff4444/ffffff",
    duration: "12 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Massachusetts Institute of Technology",
    prerequisites: ["PHP", "Go", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Machine Learning",
        content: "nunc id aliquam fermentum",
      },
      { week: 2, topic: "Cybersecurity", content: "mi nec ultrices tristique" },
      {
        week: 3,
        topic: "Software Engineering",
        content:
          "consectetur adipiscing elit. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
      {
        week: 4,
        topic: "Web Development",
        content: "nunc id aliquam fermentum",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "efoystone0@hostgator.com" },
      { id: 2, name: "John Smith", email: "gfrend1@gov.uk" },
      { id: 3, name: "Michael Davis", email: "enancarrow2@desdev.cn" },
      { id: 4, name: "Emma Wilson", email: "jcasacchia3@harvard.edu" },
      { id: 5, name: "John Smith", email: "rtampin4@nydailynews.com" },
      { id: 6, name: "Emily Johnson", email: "rthrelfall5@seesaa.net" },
    ],
  },
  {
    id: 36,
    name: "Computer Networks",
    instructor: "Chloe Ward",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/195x100.png/ff4444/ffffff",
    duration: "6 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Stanford University",
    prerequisites: ["Rust", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Database Management Systems",
        content: "mi nec ultrices tristique",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "fbateman0@g.co" },
      { id: 2, name: "Michael Davis", email: "bocorr1@stumbleupon.com" },
      { id: 3, name: "John Smith", email: "zmcgrale2@networksolutions.com" },
      { id: 4, name: "Emma Wilson", email: "pfleckno3@mapy.cz" },
      { id: 5, name: "Daniel Thompson", email: "scaffin4@friendfeed.com" },
      { id: 6, name: "John Smith", email: "mgunter5@ted.com" },
    ],
  },
  {
    id: 37,
    name: "Software Engineering",
    instructor: "Ryan Brooks",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/213x100.png/ff4444/ffffff",
    duration: "4 weeks",
    Schedule: "Monday-Friday",
    location: "University of Toronto",
    prerequisites: ["Java", "Swift", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "nunc id aliquam fermentum",
      },
      {
        week: 2,
        topic: "Web Development",
        content: "mi nec ultrices tristique",
      },
    ],
    students: [
      { id: 1, name: "Daniel Thompson", email: "dfearby0@marriott.com" },
    ],
  },
  {
    id: 38,
    name: "Web Development",
    instructor: "Natalie Bailey",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/142x100.png/ff4444/ffffff",
    duration: "10 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of California",
    prerequisites: ["Rust", "Swift"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "mi nec ultrices tristique",
      },
      {
        week: 2,
        topic: "Web Development",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 3,
        topic: "Introduction to Computer Science",
        content: "Lorem ipsum dolor sit amet",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "mbeedell0@google.ca" },
      { id: 2, name: "Emma Wilson", email: "sbrotherick1@timesonline.co.uk" },
      { id: 3, name: "John Smith", email: "shoodless2@arizona.edu" },
      { id: 4, name: "Daniel Thompson", email: "mkraut3@ca.gov" },
    ],
  },
  {
    id: 39,
    name: "Machine Learning",
    instructor: "Samuel Foster",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/122x100.png/ff4444/ffffff",
    duration: "8 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of Cambridge",
    prerequisites: ["Swift", "Ruby", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content: "est urna feugiat justo",
      },
      { week: 2, topic: "Web Development", content: "lobortis nunc sed" },
      {
        week: 3,
        topic: "Introduction to Computer Science",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 4,
        topic: "Database Management Systems",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "ddyment0@cnet.com" },
      { id: 2, name: "Emma Wilson", email: "pbesnardeau1@shutterfly.com" },
      { id: 3, name: "John Smith", email: "wjoslow2@i2i.jp" },
      { id: 4, name: "Emma Wilson", email: "molyff3@cocolog-nifty.com" },
      { id: 5, name: "Emily Johnson", email: "bdemangel4@google.co.jp" },
    ],
  },
  {
    id: 40,
    name: "Cybersecurity",
    instructor: "Lily Phillips",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/156x100.png/5fa2dd/ffffff",
    duration: "8 weeks",
    Schedule: "Monday-Friday",
    location: "Harvard University",
    prerequisites: ["JavaScript", "Python", "Go"],
    syllabus: [
      {
        week: 1,
        topic: "Computer Networks",
        content: "est urna feugiat justo",
      },
      {
        week: 2,
        topic: "Software Engineering",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
      {
        week: 3,
        topic: "Web Development",
        content: "Lorem ipsum dolor sit amet",
      },
      {
        week: 4,
        topic: "Introduction to Computer Science",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "jgroucock0@sciencedirect.com" },
      { id: 2, name: "John Smith", email: "llehrle1@ameblo.jp" },
      { id: 3, name: "Michael Davis", email: "uklambt2@imageshack.us" },
      { id: 4, name: "Michael Davis", email: "ecradey3@a8.net" },
      { id: 5, name: "John Smith", email: "cmullord4@flickr.com" },
    ],
  },
  {
    id: 41,
    name: "Introduction to Computer Science",
    instructor: "Jonathan Simmons",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/207x100.png/dddddd/000000",
    duration: "12 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Harvard University",
    prerequisites: ["JavaScript", "Swift"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "bscawn0@yolasite.com" },
      { id: 2, name: "Michael Davis", email: "gdurran1@fda.gov" },
      { id: 3, name: "Michael Davis", email: "smarkey2@google.com.br" },
      { id: 4, name: "John Smith", email: "nladon3@imdb.com" },
    ],
  },
  {
    id: 42,
    name: "Data Structures and Algorithms",
    instructor: "Hannah Ross",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/172x100.png/ff4444/ffffff",
    duration: "8 weeks",
    Schedule: "Monday-Friday",
    location: "University of California",
    prerequisites: ["JavaScript", "Swift"],
    syllabus: [
      {
        week: 1,
        topic: "Database Management Systems",
        content: "lobortis nunc sed",
      },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content: "nunc id aliquam fermentum",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "aedmed0@rakuten.co.jp" },
      { id: 2, name: "John Smith", email: "dfiorentino1@com.com" },
    ],
  },
  {
    id: 43,
    name: "Operating Systems",
    instructor: "Gabriel Bell",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/138x100.png/5fa2dd/ffffff",
    duration: "6 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Columbia University",
    prerequisites: ["Python", "Rust"],
    syllabus: [
      {
        week: 1,
        topic: "Web Development",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 2,
        topic: "Machine Learning",
        content: "mi nec ultrices tristique",
      },
      { week: 3, topic: "Machine Learning", content: "est urna feugiat justo" },
      {
        week: 4,
        topic: "Introduction to Computer Science",
        content: "Lorem ipsum dolor sit amet",
      },
    ],
    students: [
      { id: 1, name: "Daniel Thompson", email: "akoppelmann0@skyrock.com" },
      { id: 2, name: "Emma Wilson", email: "fbroadhurst1@berkeley.edu" },
      { id: 3, name: "Michael Davis", email: "gpfeiffer2@bbb.org" },
    ],
  },
  {
    id: 44,
    name: "Database Management Systems",
    instructor: "Victoria Perry",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/187x100.png/5fa2dd/ffffff",
    duration: "10 weeks",
    Schedule: "Monday-Friday",
    location: "Columbia University",
    prerequisites: ["JavaScript", "Swift", "Python"],
    syllabus: [
      {
        week: 1,
        topic: "Software Engineering",
        content: "nunc id aliquam fermentum",
      },
      {
        week: 2,
        topic: "Machine Learning",
        content: "mi nec ultrices tristique",
      },
      {
        week: 3,
        topic: "Database Management Systems",
        content:
          "consectetur adipiscing elit. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
      {
        week: 4,
        topic: "Computer Networks",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "akanter0@thetimes.co.uk" },
      { id: 2, name: "Emma Wilson", email: "bdirr1@usnews.com" },
      { id: 3, name: "Michael Davis", email: "abrussell2@indiegogo.com" },
    ],
  },
  {
    id: 45,
    name: "Artificial Intelligence",
    instructor: "Christopher Cox",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/140x100.png/dddddd/000000",
    duration: "6 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Harvard University",
    prerequisites: ["Ruby", "Swift", "Rust"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "est urna feugiat justo",
      },
    ],
    students: [{ id: 1, name: "Emma Wilson", email: "ejanecek0@google.de" }],
  },
  {
    id: 46,
    name: "Computer Networks",
    instructor: "Lauren Hughes",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/247x100.png/dddddd/000000",
    duration: "4 weeks",
    Schedule: "Tuesday-Saturday",
    location: "University of California",
    prerequisites: ["Go", "Java"],
    syllabus: [
      {
        week: 1,
        topic: "Data Structures and Algorithms",
        content: "est urna feugiat justo",
      },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content: "est urna feugiat justo",
      },
      {
        week: 3,
        topic: "Computer Networks",
        content: "nunc id aliquam fermentum",
      },
      {
        week: 4,
        topic: "Operating Systems",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "ktwatt0@istockphoto.com" },
      { id: 2, name: "John Smith", email: "kizac1@qq.com" },
      { id: 3, name: "John Smith", email: "tstoate2@tmall.com" },
      { id: 4, name: "Emily Johnson", email: "cbethell3@yellowpages.com" },
    ],
  },
  {
    id: 47,
    name: "Software Engineering",
    instructor: "Andrew Jenkins",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/117x100.png/cc0000/ffffff",
    duration: "6 weeks",
    Schedule: "Monday-Friday",
    location: "Yale University",
    prerequisites: ["Ruby", "Java", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "mi nec ultrices tristique",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "lrowbottom0@slideshare.net" },
      { id: 2, name: "Emily Johnson", email: "dyakovl1@goo.ne.jp" },
      { id: 3, name: "Daniel Thompson", email: "tdoorey2@usda.gov" },
      { id: 4, name: "Daniel Thompson", email: "dcasali3@berkeley.edu" },
      { id: 5, name: "John Smith", email: "sneilus4@opera.com" },
      { id: 6, name: "Michael Davis", email: "madnam5@shop-pro.jp" },
    ],
  },
  {
    id: 48,
    name: "Web Development",
    instructor: "Avery Gray",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/102x100.png/cc0000/ffffff",
    duration: "12 weeks",
    Schedule: "Monday-Friday",
    location: "University of Cambridge",
    prerequisites: ["PHP", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content: "mi nec ultrices tristique",
      },
      { week: 2, topic: "Cybersecurity", content: "nunc id aliquam fermentum" },
      {
        week: 3,
        topic: "Database Management Systems",
        content: "nisl turpis commodo neque",
      },
      {
        week: 4,
        topic: "Cybersecurity",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "pfriar0@tinypic.com" },
      { id: 2, name: "Daniel Thompson", email: "baxford1@zdnet.com" },
      { id: 3, name: "Emma Wilson", email: "hlawrenceson2@nih.gov" },
    ],
  },
  {
    id: 49,
    name: "Machine Learning",
    instructor: "Nicholas Butler",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/190x100.png/dddddd/000000",
    duration: "4 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Stanford University",
    prerequisites: ["Ruby", "Go", "JavaScript"],
    syllabus: [
      {
        week: 1,
        topic: "Machine Learning",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 2,
        topic: "Machine Learning",
        content: "nunc id aliquam fermentum",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "gdockwra0@ustream.tv" },
      { id: 2, name: "Emily Johnson", email: "kpoley1@cloudflare.com" },
      { id: 3, name: "John Smith", email: "bpainswick2@diigo.com" },
      { id: 4, name: "Emily Johnson", email: "nbrewett3@goo.ne.jp" },
      { id: 5, name: "John Smith", email: "ubrashier4@trellian.com" },
      { id: 6, name: "Emily Johnson", email: "jprestige5@hexun.com" },
    ],
  },
  {
    id: 50,
    name: "Cybersecurity",
    instructor: "Ella Long",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/179x100.png/cc0000/ffffff",
    duration: "12 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Princeton University",
    prerequisites: ["C++", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content: "mi nec ultrices tristique",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content: "lobortis nunc sed",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "bstoll0@apple.com" },
      { id: 2, name: "John Smith", email: "wtolcher1@liveinternet.ru" },
      { id: 3, name: "Emily Johnson", email: "lpimbley2@booking.com" },
      { id: 4, name: "Emma Wilson", email: "urigardeau3@reference.com" },
      { id: 5, name: "Emma Wilson", email: "emarlowe4@amazon.co.uk" },
      { id: 6, name: "Daniel Thompson", email: "rlozano5@theglobeandmail.com" },
    ],
  },
  {
    id: 51,
    name: "Introduction to Computer Science",
    instructor: "John Smith",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/129x100.png/cc0000/ffffff",
    duration: "6 weeks",
    Schedule: "Monday-Friday",
    location: "Harvard University",
    prerequisites: ["Swift", "Java"],
    syllabus: [
      {
        week: 1,
        topic: "Operating Systems",
        content: "Lorem ipsum dolor sit amet",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "lpetrello0@mashable.com" },
    ],
  },
  {
    id: 52,
    name: "Data Structures and Algorithms",
    instructor: "Emily Johnson",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/108x100.png/cc0000/ffffff",
    duration: "8 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Massachusetts Institute of Technology",
    prerequisites: ["Ruby", "JavaScript"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "kgiberd0@amazon.co.jp" },
      { id: 2, name: "John Smith", email: "mpumphrey1@noaa.gov" },
    ],
  },
  {
    id: 53,
    name: "Operating Systems",
    instructor: "Michael Davis",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/137x100.png/ff4444/ffffff",
    duration: "12 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Princeton University",
    prerequisites: ["Go", "Java", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Machine Learning",
        content: "nisl turpis commodo neque",
      },
      {
        week: 2,
        topic: "Cybersecurity",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus.",
      },
    ],
    students: [
      { id: 1, name: "Daniel Thompson", email: "sjearum0@vinaora.com" },
      { id: 2, name: "Emily Johnson", email: "lchaffyn1@businessinsider.com" },
      { id: 3, name: "Michael Davis", email: "btrulock2@elpais.com" },
    ],
  },
  {
    id: 54,
    name: "Database Management Systems",
    instructor: "Jessica Wilson",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/150x100.png/ff4444/ffffff",
    duration: "6 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of Oxford",
    prerequisites: ["JavaScript", "Go"],
    syllabus: [
      {
        week: 1,
        topic: "Machine Learning",
        content: "nisl turpis commodo neque",
      },
      {
        week: 2,
        topic: "Machine Learning",
        content: "Lorem ipsum dolor sit amet",
      },
      {
        week: 3,
        topic: "Software Engineering",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "gprestner0@irs.gov" },
      { id: 2, name: "Michael Davis", email: "hdabbes1@nasa.gov" },
      { id: 3, name: "Michael Davis", email: "rhartshorne2@admin.ch" },
    ],
  },
  {
    id: 55,
    name: "Artificial Intelligence",
    instructor: "David Thompson",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/123x100.png/ff4444/ffffff",
    duration: "10 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Princeton University",
    prerequisites: ["Python", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Computer Networks",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 2,
        topic: "Machine Learning",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus.",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "clongcaster0@geocities.jp" },
    ],
  },
  {
    id: 56,
    name: "Computer Networks",
    instructor: "Sarah Anderson",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/222x100.png/cc0000/ffffff",
    duration: "6 weeks",
    Schedule: "Monday-Friday",
    location: "Harvard University",
    prerequisites: ["JavaScript", "Swift", "Python"],
    syllabus: [
      {
        week: 1,
        topic: "Database Management Systems",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      { week: 2, topic: "Cybersecurity", content: "nisl turpis commodo neque" },
      {
        week: 3,
        topic: "Artificial Intelligence",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "chuleatt0@cornell.edu" },
      { id: 2, name: "Michael Davis", email: "cardley1@youtube.com" },
    ],
  },
  {
    id: 57,
    name: "Software Engineering",
    instructor: "Daniel Martinez",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/246x100.png/dddddd/000000",
    duration: "6 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Harvard University",
    prerequisites: ["Java", "Swift"],
    syllabus: [
      {
        week: 1,
        topic: "Software Engineering",
        content: "est urna feugiat justo",
      },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content: "Lorem ipsum dolor sit amet",
      },
      {
        week: 3,
        topic: "Database Management Systems",
        content: "est urna feugiat justo",
      },
      {
        week: 4,
        topic: "Computer Networks",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "astrongman0@1688.com" },
      { id: 2, name: "John Smith", email: "cmardlin1@prlog.org" },
      { id: 3, name: "Michael Davis", email: "skettles2@wufoo.com" },
    ],
  },
  {
    id: 58,
    name: "Web Development",
    instructor: "Olivia Taylor",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/200x100.png/dddddd/000000",
    duration: "10 weeks",
    Schedule: "Monday-Friday",
    location: "University of California",
    prerequisites: ["Swift", "Rust", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Web Development",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
      {
        week: 2,
        topic: "Machine Learning",
        content: "nisl turpis commodo neque",
      },
      {
        week: 3,
        topic: "Machine Learning",
        content:
          "consectetur adipiscing elit. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "lferraro0@go.com" },
      { id: 2, name: "Michael Davis", email: "penrrico1@bbc.co.uk" },
    ],
  },
  {
    id: 59,
    name: "Machine Learning",
    instructor: "Matthew Hernandez",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/232x100.png/ff4444/ffffff",
    duration: "8 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of Cambridge",
    prerequisites: ["Swift", "Go"],
    syllabus: [
      {
        week: 1,
        topic: "Web Development",
        content: "nisl turpis commodo neque",
      },
      {
        week: 2,
        topic: "Database Management Systems",
        content:
          "id aliquet mi mauris nec urna. Sed nec semper nunc. Aliquam erat volutpat. Sed euismod",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "kmatevushev0@theguardian.com" },
      { id: 2, name: "Daniel Thompson", email: "whakeworth1@examiner.com" },
    ],
  },
  {
    id: 60,
    name: "Cybersecurity",
    instructor: "Sophia Moore",
    description: "Close",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/143x100.png/cc0000/ffffff",
    duration: "10 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Stanford University",
    prerequisites: ["JavaScript", "Python", "Rust"],
    syllabus: [
      {
        week: 1,
        topic: "Database Management Systems",
        content:
          "in ultrices mi enim non nunc. Sed id semper turpis. Sed et ligula id nunc tincidunt faucibus. Sed id purus sed tortor tincidunt luctus. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
      {
        week: 2,
        topic: "Software Engineering",
        content: "Lorem ipsum dolor sit amet",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "csonley0@bbc.co.uk" },
      { id: 2, name: "Emma Wilson", email: "fmelling1@sogou.com" },
      { id: 3, name: "Emily Johnson", email: "ebeals2@people.com.cn" },
    ],
  },
  {
    id: 61,
    name: "Introduction to Computer Science",
    instructor: "Andrew Clark",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/118x100.png/dddddd/000000",
    duration: "8 weeks",
    Schedule: "Wednesday-Sunday",
    location: "University of Oxford",
    prerequisites: ["Ruby", "Rust", "Python"],
    syllabus: [
      {
        week: 1,
        topic: "Introduction to Computer Science",
        content: "est urna feugiat justo",
      },
      {
        week: 2,
        topic: "Artificial Intelligence",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      {
        week: 3,
        topic: "Database Management Systems",
        content: "est urna feugiat justo",
      },
      {
        week: 4,
        topic: "Computer Networks",
        content: "nisl turpis commodo neque",
      },
    ],
    students: [
      { id: 1, name: "Emily Johnson", email: "rhugill0@blogtalkradio.com" },
      { id: 2, name: "Daniel Thompson", email: "gvenediktov1@buzzfeed.com" },
    ],
  },
  {
    id: 62,
    name: "Data Structures and Algorithms",
    instructor: "Emma Lewis",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/246x100.png/ff4444/ffffff",
    duration: "12 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Stanford University",
    prerequisites: ["Ruby", "C++"],
    syllabus: [
      {
        week: 1,
        topic: "Artificial Intelligence",
        content: "nunc id aliquam fermentum",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "ljesse0@gov.uk" },
      { id: 2, name: "Michael Davis", email: "kplester1@nps.gov" },
      { id: 3, name: "Daniel Thompson", email: "ltowriss2@icq.com" },
      { id: 4, name: "Daniel Thompson", email: "ilamba3@apache.org" },
    ],
  },
  {
    id: 63,
    name: "Operating Systems",
    instructor: "Christopher Walker",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/146x100.png/5fa2dd/ffffff",
    duration: "8 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Stanford University",
    prerequisites: ["Java", "JavaScript"],
    syllabus: [
      {
        week: 1,
        topic: "Computer Networks",
        content:
          "consectetur adipiscing elit. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
      { week: 2, topic: "Cybersecurity", content: "nisl turpis commodo neque" },
    ],
    students: [
      { id: 1, name: "Daniel Thompson", email: "sjosilevich0@sohu.com" },
      { id: 2, name: "Emma Wilson", email: "jhayler1@imgur.com" },
      { id: 3, name: "Emma Wilson", email: "ccamblin2@hp.com" },
      { id: 4, name: "John Smith", email: "msaylor3@hugedomains.com" },
      { id: 5, name: "Daniel Thompson", email: "rcamelli4@amazon.de" },
      { id: 6, name: "John Smith", email: "mdignan5@nytimes.com" },
    ],
  },
  {
    id: 64,
    name: "Database Management Systems",
    instructor: "Ava Hall",
    description: "Inprogress",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/234x100.png/5fa2dd/ffffff",
    duration: "4 weeks",
    Schedule: "Monday-Friday",
    location: "Yale University",
    prerequisites: ["C++", "Ruby"],
    syllabus: [
      {
        week: 1,
        topic: "Data Structures and Algorithms",
        content: "lobortis nunc sed",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "tperrelle0@seesaa.net" },
      { id: 2, name: "Michael Davis", email: "lablott1@symantec.com" },
      { id: 3, name: "John Smith", email: "gtedahl2@typepad.com" },
    ],
  },
  {
    id: 65,
    name: "Artificial Intelligence",
    instructor: "Joshua Young",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/167x100.png/5fa2dd/ffffff",
    duration: "4 weeks",
    Schedule: "Tuesday-Saturday",
    location: "Stanford University",
    prerequisites: ["Python", "Go"],
    syllabus: [
      { week: 1, topic: "Software Engineering", content: "lobortis nunc sed" },
      {
        week: 2,
        topic: "Data Structures and Algorithms",
        content:
          "aliquam massa. Sed id nunc ut nunc efficitur eleifend. Nullam euismod",
      },
      { week: 3, topic: "Machine Learning", content: "lobortis nunc sed" },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "jcrummay0@yahoo.co.jp" },
      { id: 2, name: "Daniel Thompson", email: "zhunnaball1@mtv.com" },
      { id: 3, name: "Daniel Thompson", email: "hnickoles2@weibo.com" },
      { id: 4, name: "Daniel Thompson", email: "cdocwra3@sogou.com" },
      { id: 5, name: "Michael Davis", email: "bsalman4@bandcamp.com" },
      { id: 6, name: "Emma Wilson", email: "swaszczyk5@live.com" },
    ],
  },
  {
    id: 66,
    name: "Computer Networks",
    instructor: "Isabella Allen",
    description: "Open",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/111x100.png/5fa2dd/ffffff",
    duration: "8 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Yale University",
    prerequisites: ["PHP", "Java"],
    syllabus: [
      {
        week: 1,
        topic: "Machine Learning",
        content: "nisl turpis commodo neque",
      },
      {
        week: 2,
        topic: "Introduction to Computer Science",
        content:
          "consectetur adipiscing elit. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
    ],
    students: [
      { id: 1, name: "Emma Wilson", email: "jdauby0@home.pl" },
      { id: 2, name: "Michael Davis", email: "jianson1@salon.com" },
      { id: 3, name: "Emma Wilson", email: "bpiggens2@huffingtonpost.com" },
      { id: 4, name: "Daniel Thompson", email: "ltickel3@irs.gov" },
    ],
  },
  {
    id: 67,
    name: "Software Engineering",
    instructor: "Joseph Rodriguez",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/238x100.png/cc0000/ffffff",
    duration: "10 weeks",
    Schedule: "Wednesday-Sunday",
    location: "Princeton University",
    prerequisites: ["Ruby", "Rust", "JavaScript"],
    syllabus: [
      {
        week: 1,
        topic: "Data Structures and Algorithms",
        content: "Lorem ipsum dolor sit amet",
      },
      {
        week: 2,
        topic: "Software Engineering",
        content: "mi nec ultrices tristique",
      },
    ],
    students: [
      { id: 1, name: "John Smith", email: "kkovalski0@sphinn.com" },
      { id: 2, name: "John Smith", email: "ngrendon1@ow.ly" },
      { id: 3, name: "Emily Johnson", email: "ptyson2@list-manage.com" },
    ],
  },
  {
    id: 68,
    name: "Web Development",
    instructor: "Mia King",
    description: "Close",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/105x100.png/ff4444/ffffff",
    duration: "4 weeks",
    Schedule: "Monday-Friday",
    location: "Princeton University",
    prerequisites: ["Java", "Go"],
    syllabus: [
      {
        week: 1,
        topic: "Database Management Systems",
        content: "nunc id aliquam fermentum",
      },
    ],
    students: [
      { id: 1, name: "Daniel Thompson", email: "egilchrist0@photobucket.com" },
      { id: 2, name: "Michael Davis", email: "blecount1@businesswire.com" },
      { id: 3, name: "Michael Davis", email: "wdowner2@sbwire.com" },
      { id: 4, name: "John Smith", email: "whatcliffe3@livejournal.com" },
      { id: 5, name: "John Smith", email: "slepoidevin4@slideshare.net" },
    ],
  },
  {
    id: 69,
    name: "Machine Learning",
    instructor: "William Wright",
    description: "Open",
    enrollmentStatus: "open",
    thumbnail: "http://dummyimage.com/179x100.png/dddddd/000000",
    duration: "12 weeks",
    Schedule: "Monday-Friday",
    location: "Harvard University",
    prerequisites: ["Go", "Swift"],
    syllabus: [
      {
        week: 1,
        topic: "Software Engineering",
        content: "mi nec ultrices tristique",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "tbowser0@yellowbook.com" },
      { id: 2, name: "Michael Davis", email: "caltimas1@cam.ac.uk" },
      { id: 3, name: "John Smith", email: "dday2@icio.us" },
    ],
  },
  {
    id: 70,
    name: "Cybersecurity",
    instructor: "Abigail Hill",
    description: "Inprogress",
    enrollmentStatus: "close",
    thumbnail: "http://dummyimage.com/193x100.png/ff4444/ffffff",
    duration: "8 weeks",
    Schedule: "Monday-Friday",
    location: "Harvard University",
    prerequisites: ["Java", "Swift"],
    syllabus: [
      { week: 1, topic: "Machine Learning", content: "est urna feugiat justo" },
      {
        week: 2,
        topic: "Software Engineering",
        content: "nisl turpis commodo neque",
      },
      {
        week: 3,
        topic: "Artificial Intelligence",
        content:
          "consectetur adipiscing elit. Sed ac mauris nec nisl aliquam ultrices. Nulla facilisi. Sed non mauris in nunc ultricies mattis. Sed at mauris euismod",
      },
    ],
    students: [
      { id: 1, name: "Michael Davis", email: "eguilleton0@google.co.uk" },
      { id: 2, name: "Michael Davis", email: "sbraunes1@diigo.com" },
      { id: 3, name: "Daniel Thompson", email: "rrival2@de.vu" },
      { id: 4, name: "Emma Wilson", email: "cstaterfield3@fda.gov" },
      { id: 5, name: "Emma Wilson", email: "jchallicum4@auda.org.au" },
      { id: 6, name: "Emily Johnson", email: "askrines5@earthlink.net" },
    ],
  },
];
module.exports = data;
